FROM node:18.12.1-alpine

ENV PNPM_HOME=/root/.local/share/pnpm
ENV PATH=${PNPM_HOME}:${PATH}

RUN npm install -g pnpm \
    && pnpm config set store-dir ${PNPM_HOME} \
    && pnpm add -g @nestjs/cli
